addSbtPlugin("com.lucidchart"    % "sbt-scalafmt"        % "1.3")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"             % "0.9.3")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager" % "1.2.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "2.0.0")
addSbtPlugin("io.spray"          % "sbt-revolver"        % "0.8.0")
